using Fleet.Shared.Themes;

namespace Fleet.Platform.Nvim;

public static class NvimTheme
{
    public const string PaletteFile = "palette.lua";

    public static string Generate(ThemePalette theme)
    {
        var roles = string.Join(
            "\n", ThemePalette.RoleNames.Select(r => $"  {r} = \"{theme.Role(r)}\","));

        return $$"""
            -- generated by fleet from the '{{theme.Name}}' theme; fleet rewrites this file on every theme change.
            return {
              name = "{{Escape(theme.Name)}}",
              title = "{{Escape(theme.Title)}}",
              light = {{(theme.Light ? "true" : "false")}},
            {{roles}}
              ansi = { {{List(theme.Ansi)}} },
              brights = { {{List(theme.Brights)}} },
            }

            """.ReplaceLineEndings("\n");
    }

    private static string List(IReadOnlyList<string> colors) =>
        string.Join(", ", colors.Select(c => $"\"{c}\""));

    private static string Escape(string text) =>
        text.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
