using Fleet.Shared.Keybinds;
using Fleet.Shared.Keybinds.Models;

namespace Fleet.Platform.Nvim;

public static class NvimKeybinds
{
    public const string GeneratedFile = "keybinds.generated.lua";

    public const string UserModuleFile = "fleet-keys.lua";

    public const string GeneratedHeader =
        "-- generated by fleet from its keybinds; fleet rewrites this file whenever it installs its nvim config.";

    public const string UserModuleHeader =
        "-- generated by fleet from its keybinds for your own nvim config; fleet rewrites it, so don't edit it.\n"
        + "-- Load it with dofile('<path to this file>').setup(), or setup({ ['focus-left'] = false }) to skip a keybind.";

    public static string Generate(IReadOnlyList<KeybindBinding> bindings) => Module(GeneratedHeader, bindings);

    public static string GenerateUserModule(IReadOnlyList<KeybindBinding> bindings) =>
        Module(UserModuleHeader, bindings);

    private static string Module(string header, IReadOnlyList<KeybindBinding> bindings)
    {
        var rows = string.Concat(bindings
            .Where(b => b.Contexts.Count > 0)
            .Select(b => $"  {{ id = {Quote(b.Id)}, action = {Quote(b.Action)}, lhs = {Quote(NvimChord.Lhs(b.Chord))}, "
                + $"modes = {{ {string.Join(", ", b.Contexts.Select(Quote))} }} }},\n"));

        return (header + "\n" + $$"""
            local M = {}

            M.resize_step = 3

            M.bindings = {
            {{rows}}}

            {{Runtime}}
            """).ReplaceLineEndings("\n");
    }

    private const string Runtime = """
        local directions = { left = 'h', down = 'j', up = 'k', right = 'l' }

        local function claude_terminal(buf)
          local command = vim.api.nvim_buf_get_name(buf):match('^term://.-//%d+:(.*)$')
          return command ~= nil and command:lower():find('claude', 1, true) ~= nil
        end

        local function resize(dir)
          local ok, splits = pcall(require, 'smart-splits')
          if ok and type(splits) == 'table' and splits['resize_' .. dir] then
            splits['resize_' .. dir]()
            return
          end
          local vertical = dir == 'left' or dir == 'right'
          local grow = dir == 'right' or dir == 'down'
          if vim.fn.winnr(vertical and 'l' or 'j') == vim.fn.winnr() then
            grow = not grow
          end
          vim.cmd((vertical and 'vertical ' or '') .. 'resize ' .. (grow and '+' or '-') .. M.resize_step)
        end

        function M.attach_claude(buf, skip)
          skip = skip or {}
          for _, b in ipairs(M.bindings) do
            if b.action == 'claude-normal-mode' and skip[b.id] ~= false then
              vim.keymap.set(b.modes, b.lhs, '<C-\\><C-n>', { buffer = buf, desc = 'Leave terminal mode' })
            end
          end
        end

        function M.setup(skip)
          skip = skip or {}
          for _, b in ipairs(M.bindings) do
            local focus = b.action:match('^focus%-(%a+)$')
            local size = b.action:match('^resize%-(%a+)$')
            if skip[b.id] == false then
            elseif focus and directions[focus] and vim.tbl_contains(b.modes, 'n') then
              vim.keymap.set('n', b.lhs, '<C-w>' .. directions[focus], { desc = 'Window ' .. directions[focus] })
            elseif size and directions[size] then
              vim.keymap.set(b.modes, b.lhs, function() resize(size) end, { desc = 'Resize ' .. size })
            end
          end

          vim.api.nvim_create_autocmd('TermOpen', {
            group = vim.api.nvim_create_augroup('fleet_keybinds', { clear = true }),
            callback = function(ev)
              if claude_terminal(ev.buf) then
                M.attach_claude(ev.buf, skip)
              end
            end,
          })
        end

        return M

        """;

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
}
