<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ptyspike</AssemblyName>
    <RootNamespace>PtySpike</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <IlcTreatWarningsAsErrors>false</IlcTreatWarningsAsErrors>
    <NoWarn>IL2026;IL2104;IL3053;IL3050;IL2075;IL2072</NoWarn>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Porta.Pty" Version="1.0.7" />
  </ItemGroup>

</Project>
