using System.Text;
using Fleet.Platform.Mux.WezTerm.Models;
using Fleet.Shared.Keymap;
using Fleet.Shared.Keymap.Enums;
using Fleet.Ui;

namespace Fleet.Platform.Mux.WezTerm;

public static class WezTermKeybinds
{
    private const string TableName = "fleet";

    private static readonly FleetAction[] MenuActions =
    [
        FleetAction.NewAgent,
        FleetAction.ChangeHarness,
        FleetAction.ToggleHidden,
        FleetAction.RemoveAgent,
        FleetAction.AddRepository,
        FleetAction.RemoveRepository,
        FleetAction.EditKeybinds,
        FleetAction.OpenProject,
        FleetAction.Close,
    ];

    public static string Generate(Keymap keymap, string fleetExecutable, string workspaceRequest)
    {
        var chord = WezTermChord.From(keymap.PrefixText);
        var menu = MenuKeys.Assign(MenuActions, keymap.Config.Bindings);
        var exe = fleetExecutable.Replace("\\", "\\\\", StringComparison.Ordinal);
        var request = workspaceRequest.Replace("\\", "\\\\", StringComparison.Ordinal);

        var sb = new StringBuilder();

        sb.AppendLine("-- generated by: fleet apply-keybinds");
        sb.AppendLine("-- edit fleet's keybinds instead of this file; it is overwritten.");
        sb.AppendLine("--");
        sb.AppendLine("-- add to .wezterm.lua:");
        sb.AppendLine("--   local fleet = require 'fleet'");
        sb.AppendLine("--   fleet.apply(config)");
        sb.AppendLine();
        sb.AppendLine("local wezterm = require 'wezterm'");
        sb.AppendLine("local act = wezterm.action");
        sb.AppendLine();
        sb.AppendLine("local M = {}");
        sb.AppendLine();
        sb.AppendLine($"M.fleet = '{exe}'");
        sb.AppendLine("M.showing_menu = false");
        sb.AppendLine();
        sb.AppendLine("-- The menu belongs to windows fleet is actually running in. A fleet dashboard");
        sb.AppendLine("-- marks its pane with a WezTerm user var holding the project name; without one");
        sb.AppendLine("-- the chord is forwarded to the pane untouched, so unrelated windows keep the");
        sb.AppendLine("-- key.");
        sb.AppendLine("local function fleet_project(window)");
        sb.AppendLine("  local ok, tabs = pcall(function()");
        sb.AppendLine("    return window:mux_window():tabs()");
        sb.AppendLine("  end)");
        sb.AppendLine();
        sb.AppendLine("  if not ok or not tabs then");
        sb.AppendLine("    return nil");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  for _, tab in ipairs(tabs) do");
        sb.AppendLine("    for _, p in ipairs(tab:panes()) do");
        sb.AppendLine("      local vars = p:get_user_vars()");
        sb.AppendLine($"      local project = vars and vars['{WezTermUserVars.FleetVar}']");
        sb.AppendLine("      if project and project ~= '' then");
        sb.AppendLine("        wezterm.log_info('fleet: dashboard pane found for ' .. project)");
        sb.AppendLine("        return project");
        sb.AppendLine("      end");
        sb.AppendLine("    end");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  wezterm.log_info('fleet: no dashboard pane in this window, forwarding the key')");
        sb.AppendLine("  return nil");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("-- Actions the running dashboard renders itself. Sending these to the dashboard");
        sb.AppendLine("-- keeps the form inside the pane it belongs to instead of squeezing a third");
        sb.AppendLine("-- column into the window.");
        sb.AppendLine("M.dashboard_actions = {");

        foreach (var action in MenuActions.Where(DashboardActions.IsServed))
        {
            sb.AppendLine($"  ['{FleetActionIds.For(action)}'] = true,");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("-- The CLI cannot switch workspaces: activate-pane reports success but leaves");
        sb.AppendLine("-- the client where it was. Hidden agents live in their own workspace, so fleet");
        sb.AppendLine("-- asks for a switch by writing a file and this handler performs it. update-status");
        sb.AppendLine("-- fires about once a second, which is the only timer wezterm offers.");
        sb.AppendLine($"M.workspace_request = '{request}'");
        sb.AppendLine();
        sb.AppendLine("wezterm.on('update-status', function(window, _pane)");
        sb.AppendLine($"  if window:active_key_table() == '{TableName}' then");
        sb.AppendLine("    local parts = {}");
        sb.AppendLine("    for _, item in ipairs(M.menu) do");
        sb.AppendLine("      parts[#parts + 1] = item.key .. ' ' .. item.label");
        sb.AppendLine("    end");
        sb.AppendLine("    window:set_left_status(' fleet  ' .. table.concat(parts, '   ') .. ' ')");
        sb.AppendLine("    M.showing_menu = true");
        sb.AppendLine("  elseif M.showing_menu then");
        sb.AppendLine("    M.showing_menu = false");
        sb.AppendLine("    window:set_left_status('')");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  local handle = io.open(M.workspace_request, 'r')");
        sb.AppendLine();
        sb.AppendLine("  if not handle then");
        sb.AppendLine("    return");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  local wanted = handle:read('*a')");
        sb.AppendLine("  handle:close()");
        sb.AppendLine("  os.remove(M.workspace_request)");
        sb.AppendLine();
        sb.AppendLine("  wanted = wanted and wanted:gsub('%s+$', '')");
        sb.AppendLine();
        sb.AppendLine("  if not wanted or wanted == '' then");
        sb.AppendLine("    return");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  if window:active_workspace() == wanted then");
        sb.AppendLine("    return");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  wezterm.log_info('fleet: switching to workspace ' .. wanted)");
        sb.AppendLine("  window:perform_action(act.SwitchToWorkspace { name = wanted }, _pane)");
        sb.AppendLine("end)");
        sb.AppendLine();
        sb.AppendLine("-- One key per entry, not fuzzy matching. The prefix activates a one-shot key");
        sb.AppendLine("-- table; the next key runs its action and the table pops. The entries are");
        sb.AppendLine("-- listed in the status bar while the table is active, since wezterm draws no");
        sb.AppendLine("-- menu for a key table.");
        sb.AppendLine("M.menu = {");

        foreach (var entry in menu)
        {
            var id = FleetActionIds.For(entry.Action);
            sb.AppendLine(
                $"  {{ key = '{entry.Key}', label = '{entry.Label}', id = '{id}' }},");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function M.run(window, pane, id)");
        sb.AppendLine("  local project = fleet_project(window)");
        sb.AppendLine();
        sb.AppendLine("  if project and M.dashboard_actions[id] then");
        sb.AppendLine("    wezterm.background_child_process {");
        sb.AppendLine("      M.fleet, 'request', '--action', id, '--project', project,");
        sb.AppendLine("    }");
        sb.AppendLine("    return");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  window:perform_action(");
        sb.AppendLine("    act.SplitPane {");
        sb.AppendLine("      direction = 'Right',");
        sb.AppendLine("      size = { Percent = 45 },");
        sb.AppendLine("      command = { args = { M.fleet, 'menu', '--action', id } },");
        sb.AppendLine("    },");
        sb.AppendLine("    pane");
        sb.AppendLine("  )");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("function M.apply(config)");
        sb.AppendLine("  config.keys = config.keys or {}");
        sb.AppendLine("  config.key_tables = config.key_tables or {}");
        sb.AppendLine();
        sb.AppendLine("  local entries = {}");
        sb.AppendLine();
        sb.AppendLine("  for _, item in ipairs(M.menu) do");
        sb.AppendLine("    local id = item.id");
        sb.AppendLine("    table.insert(entries, {");
        sb.AppendLine("      key = item.key,");
        sb.AppendLine("      action = wezterm.action_callback(function(window, pane)");
        sb.AppendLine("        M.run(window, pane, id)");
        sb.AppendLine("      end),");
        sb.AppendLine("    })");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  table.insert(entries, { key = 'Escape', action = act.PopKeyTable })");
        sb.AppendLine();
        sb.AppendLine($"  config.key_tables['{TableName}'] = entries");
        sb.AppendLine();
        sb.AppendLine("  table.insert(config.keys, {");
        sb.AppendLine($"    key = '{chord.Key}',");
        sb.AppendLine($"    mods = '{chord.Mods}',");
        sb.AppendLine("    action = wezterm.action_callback(function(window, pane)");
        sb.AppendLine("      if not fleet_project(window) then");
        sb.AppendLine("        window:perform_action(");
        sb.AppendLine($"          act.SendKey {{ key = '{chord.Key}', mods = '{chord.Mods}' }},");
        sb.AppendLine("          pane");
        sb.AppendLine("        )");
        sb.AppendLine("        return");
        sb.AppendLine("      end");
        sb.AppendLine();
        sb.AppendLine("      window:perform_action(");
        sb.AppendLine($"        act.ActivateKeyTable {{ name = '{TableName}', one_shot = true }},");
        sb.AppendLine("        pane");
        sb.AppendLine("      )");
        sb.AppendLine("    end),");
        sb.AppendLine("  })");
        sb.AppendLine();
        sb.AppendLine("  return config");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("-- Compatibility with the predecessor's call shape. A .wezterm.lua written for");
        sb.AppendLine("-- the old Go fleet calls fleet.setup(config, opts); its pcall guards only the");
        sb.AppendLine("-- require, so a module without setup would fail the whole config at load.");
        sb.AppendLine("function M.setup(config, _opts)");
        sb.AppendLine("  return M.apply(config)");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("return M");

        return sb.ToString();
    }
}
