namespace Fleet.Platform.Mux.WezTerm;

public static class WezTermInstance
{
    public const string Domain = "fleet";

    public static string SocketPath(string root) => Path.Combine(root, "fleet.sock");

    public static string ConfigFile(string root) => Path.Combine(root, "fleet-instance.lua");

    public static string Config(string socketPath, string moduleDirectory)
    {
        var escapedSocket = socketPath.Replace("\\", "\\\\", StringComparison.Ordinal);

        var modulePattern =
            moduleDirectory.Replace("\\", "\\\\", StringComparison.Ordinal) + "\\\\?.lua";

        return string.Join(
            "\n",
            "-- generated by: fleet setup",
            "-- this is fleet's own isolated WezTerm process; it is not your terminal's",
            "-- config, and fleet never wires anything into your own wezterm.lua.",
            "local wezterm = require 'wezterm'",
            "local config = wezterm.config_builder()",
            string.Empty,
            "config.unix_domains = {",
            "  {",
            $"    name = '{Domain}',",
            $"    socket_path = '{escapedSocket}',",
            "  },",
            "}",
            string.Empty,
            $"config.default_domain = '{Domain}'",
            $"config.default_gui_startup_args = {{ 'connect', '{Domain}' }}",
            string.Empty,
            $"package.path = package.path .. ';{modulePattern}'",
            string.Empty,
            "local ok_theme, theme = pcall(require, 'fleet-theme')",
            "if ok_theme then",
            "  theme.apply(config)",
            "end",
            string.Empty,
            "local ok_fleet, fleet = pcall(require, 'fleet')",
            "if ok_fleet then",
            "  fleet.apply(config)",
            "end",
            string.Empty,
            "return config",
            string.Empty);
    }
}
