using System.Text;
using Fleet.Platform.Mux.WezTerm.Models;
using Fleet.Ui;

namespace Fleet.Platform.Mux.WezTerm;

public static class WezTermKeybinds
{
    public static string Generate(Keymap keymap, string fleetExecutable)
    {
        var chord = WezTermChord.From(keymap.PrefixText);
        var exe = fleetExecutable.Replace("\\", "\\\\", StringComparison.Ordinal);

        var sb = new StringBuilder();

        sb.AppendLine("-- generated by: fleet apply-keybinds");
        sb.AppendLine("-- edit fleet's keybinds instead of this file; it is overwritten.");
        sb.AppendLine("--");
        sb.AppendLine("-- add to .wezterm.lua:");
        sb.AppendLine("--   local fleet = require 'fleet'");
        sb.AppendLine("--   fleet.apply(config)");
        sb.AppendLine();
        sb.AppendLine("local wezterm = require 'wezterm'");
        sb.AppendLine("local act = wezterm.action");
        sb.AppendLine();
        sb.AppendLine("local M = {}");
        sb.AppendLine();
        sb.AppendLine($"M.fleet = '{exe}'");
        sb.AppendLine();
        sb.AppendLine("function M.apply(config)");
        sb.AppendLine("  config.keys = config.keys or {}");
        sb.AppendLine();
        sb.AppendLine("  table.insert(config.keys, {");
        sb.AppendLine($"    key = '{chord.Key}',");
        sb.AppendLine($"    mods = '{chord.Mods}',");
        sb.AppendLine("    action = act.SplitPane {");
        sb.AppendLine("      direction = 'Right',");
        sb.AppendLine("      size = { Percent = 40 },");
        sb.AppendLine("      command = { args = { M.fleet, 'menu' } },");
        sb.AppendLine("    },");
        sb.AppendLine("  })");
        sb.AppendLine();
        sb.AppendLine("  return config");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("return M");

        return sb.ToString();
    }
}
