namespace Fleet.Platform.Mux.WezTerm;

public static class WezTermTheme
{
    public const string Module = "fleet-theme.lua";

    public static string Generate() =>
        """
        -- generated by: fleet setup
        -- Catppuccin Mocha visuals and tmux-parity keys (prefix CTRL+s).
        -- Overwritten on every 'fleet setup'; copy bits into your own config
        -- and drop the require('fleet-theme') line if you want to own them.

        local wezterm = require("wezterm")
        local act = wezterm.action

        local M = {}

        local C = {
          crust    = "#11111b",
          base     = "#1e1e2e",
          surface0 = "#313244",
          surface1 = "#45475a",
          text     = "#cdd6f4",
          lavender = "#b4befe",
        }

        local LEFT_CAP  = utf8.char(0xe0b6)
        local RIGHT_CAP = utf8.char(0xe0b4)
        local GIT_GLYPH = utf8.char(0xe0a0)

        local function is_nvim(pane)
          local proc = pane:get_foreground_process_name()
          if proc then
            local base = proc:gsub("\\", "/"):match("([^/]+)$") or proc
            base = base:lower():gsub("%.exe$", "")
            if base == "nvim" or base == "vim" then return true end
          end
          return pane:get_user_vars().IS_NVIM == "true"
        end

        local function smart_nav(key, direction)
          return {
            key = key,
            mods = "CTRL",
            action = wezterm.action_callback(function(win, pane)
              if is_nvim(pane) then
                win:perform_action(act.SendKey({ key = key, mods = "CTRL" }), pane)
              else
                win:perform_action(act.ActivatePaneDirection(direction), pane)
              end
            end),
          }
        end

        local function pill(text, accent, fg)
          return {
            { Background = { Color = C.base } },
            { Foreground = { Color = accent } },
            { Text = LEFT_CAP },
            { Background = { Color = accent } },
            { Foreground = { Color = fg } },
            { Attribute = { Intensity = "Bold" } },
            { Text = text },
            { Background = { Color = C.base } },
            { Foreground = { Color = accent } },
            { Text = RIGHT_CAP },
            "ResetAttributes",
          }
        end

        local git_cache = {}
        local GIT_TTL = 5

        local function git_branch(cwd)
          if not cwd then return nil end
          local now = os.time()
          local hit = git_cache[cwd]
          if hit and (now - hit.at) < GIT_TTL then return hit.branch end

          local ok, stdout = wezterm.run_child_process({
            "git", "-C", cwd, "branch", "--show-current",
          })
          local branch = nil
          if ok and stdout then
            branch = stdout:gsub("%s+$", "")
            if branch == "" then branch = nil end
          end
          git_cache[cwd] = { at = now, branch = branch }
          return branch
        end

        local function cwd_path(pane)
          local uri = pane:get_current_working_dir()
          if not uri then return nil end
          local path = type(uri) == "userdata" and uri.file_path
            or tostring(uri):gsub("^file://[^/]*", "")
          if not path then return nil end
          return (path:gsub("^/([A-Za-z]:)", "%1"))
        end

        function M.apply(config)
          config.font = wezterm.font_with_fallback({
            "CaskaydiaMono Nerd Font",
            "JetBrainsMono Nerd Font",
            "FiraCode Nerd Font",
            "JetBrains Mono",
          })
          config.font_size = 12.0
          config.line_height = 1.25

          config.colors = {
            foreground = "#cdd6f4",
            background = "#1e1e2e",
            cursor_bg = "#f5e0dc",
            cursor_fg = "#1e1e2e",
            cursor_border = "#f5e0dc",
            selection_fg = "#1e1e2e",
            selection_bg = "#f5e0dc",
            ansi = {
              "#45475a", "#f38ba8", "#a6e3a1", "#f9e2af",
              "#89b4fa", "#f5c2e7", "#94e2d5", "#bac2de",
            },
            brights = {
              "#585b70", "#f38ba8", "#a6e3a1", "#f9e2af",
              "#89b4fa", "#f5c2e7", "#94e2d5", "#a6adc8",
            },
          }

          config.default_cursor_style = "BlinkingBlock"
          config.cursor_blink_rate = 700

          config.window_padding = { left = 15, right = 15, top = 15, bottom = 0 }
          config.window_decorations = "RESIZE"
          config.skip_close_confirmation_for_processes_named = {}

          config.leader = { key = "s", mods = "CTRL", timeout_milliseconds = 2000 }

          config.use_fancy_tab_bar = false
          config.enable_tab_bar = true
          config.hide_tab_bar_if_only_one_tab = false
          config.tab_bar_at_bottom = false
          config.show_new_tab_button_in_tab_bar = false
          config.tab_max_width = 32
          config.status_update_interval = 1000

          config.colors.tab_bar = {
            background = C.base,
            new_tab = { bg_color = C.base, fg_color = C.surface1 },
            new_tab_hover = { bg_color = C.base, fg_color = C.lavender },
          }
          config.window_frame = {
            active_titlebar_bg = C.base,
            inactive_titlebar_bg = C.base,
          }

          local keys = {
            { key = "Enter", mods = "SHIFT", action = act.SendKey({ key = "j", mods = "CTRL" }) },
            { key = "C", mods = "CTRL|SHIFT", action = act.CopyTo("Clipboard") },
            { key = "V", mods = "CTRL|SHIFT", action = act.PasteFrom("Clipboard") },

            { key = "r", mods = "LEADER", action = act.ReloadConfiguration },
            { key = "s", mods = "LEADER|CTRL", action = act.SendKey({ key = "s", mods = "CTRL" }) },

            { key = "%", mods = "LEADER|SHIFT", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
            { key = '"', mods = "LEADER|SHIFT", action = act.SplitVertical({ domain = "CurrentPaneDomain" }) },

            { key = "h", mods = "LEADER", action = act.ActivatePaneDirection("Left") },
            { key = "j", mods = "LEADER", action = act.ActivatePaneDirection("Down") },
            { key = "k", mods = "LEADER", action = act.ActivatePaneDirection("Up") },
            { key = "l", mods = "LEADER", action = act.ActivatePaneDirection("Right") },

            smart_nav("h", "Left"),
            smart_nav("j", "Down"),
            smart_nav("k", "Up"),
            smart_nav("l", "Right"),

            { key = "c", mods = "LEADER", action = act.SpawnTab("CurrentPaneDomain") },
            { key = "n", mods = "LEADER", action = act.ActivateTabRelative(1) },
            { key = "p", mods = "LEADER", action = act.ActivateTabRelative(-1) },
            { key = "w", mods = "LEADER", action = act.ShowTabNavigator },
            { key = "&", mods = "LEADER|SHIFT", action = act.CloseCurrentTab({ confirm = true }) },
            { key = "x", mods = "LEADER", action = act.CloseCurrentPane({ confirm = true }) },
            { key = "z", mods = "LEADER", action = act.TogglePaneZoomState },
            { key = "o", mods = "LEADER", action = act.RotatePanes("Clockwise") },

            { key = "LeftArrow", mods = "ALT", action = act.ActivateTabRelative(-1) },
            { key = "RightArrow", mods = "ALT", action = act.ActivateTabRelative(1) },

            { key = "[", mods = "LEADER", action = act.ActivateCopyMode },
            { key = "]", mods = "LEADER", action = act.PasteFrom("Clipboard") },

            { key = "s", mods = "LEADER", action = act.ShowLauncherArgs({ flags = "WORKSPACES" }) },
            {
              key = ",",
              mods = "LEADER",
              action = act.PromptInputLine({
                description = "Rename tab",
                action = wezterm.action_callback(function(win, _, line)
                  if line then win:active_tab():set_title(line) end
                end),
              }),
            },

            { key = "LeftArrow", mods = "LEADER", action = act.AdjustPaneSize({ "Left", 5 }) },
            { key = "RightArrow", mods = "LEADER", action = act.AdjustPaneSize({ "Right", 5 }) },
            { key = "UpArrow", mods = "LEADER", action = act.AdjustPaneSize({ "Up", 5 }) },
            { key = "DownArrow", mods = "LEADER", action = act.AdjustPaneSize({ "Down", 5 }) },
          }

          for i = 1, 9 do
            table.insert(keys, { key = tostring(i), mods = "LEADER", action = act.ActivateTab(i - 1) })
          end

          config.keys = config.keys or {}
          for _, k in ipairs(config.keys) do
            table.insert(keys, k)
          end
          config.keys = keys

          wezterm.on("format-tab-title", function(tab, _, _, _, hover, max_width)
            local title = tab.tab_title
            if not title or #title == 0 then
              title = tab.active_pane.title
              local cwd = tab.active_pane.current_working_dir
              if cwd then
                local p = type(cwd) == "userdata" and cwd.file_path or tostring(cwd)
                title = p:match("([^/\\]+)[/\\]?$") or title
              end
            end

            local label = " " .. (tab.tab_index + 1) .. ":" .. title .. " "
            if #label > max_width then
              label = wezterm.truncate_right(label, max_width - 1) .. "… "
            end

            if tab.is_active then
              return pill(label, C.lavender, C.crust)
            end
            return pill(label, hover and C.surface1 or C.surface0, C.text)
          end)

          wezterm.on("update-status", function(win, pane)
            local has_fleet, fleet = pcall(require, "fleet")
            local session = (has_fleet and fleet.label and fleet.label(win))
              or win:active_workspace()

            win:set_left_status(wezterm.format(pill(" " .. session .. " ", C.lavender, C.crust)))

            local right = {}
            local branch = git_branch(cwd_path(pane))
            if branch then
              for _, el in ipairs(pill(" " .. GIT_GLYPH .. " " .. branch .. " ", C.surface0, C.text)) do
                table.insert(right, el)
              end
              table.insert(right, { Text = " " })
            end
            for _, el in ipairs(pill(" " .. wezterm.strftime("%H:%M %d-%b") .. " ", C.lavender, C.crust)) do
              table.insert(right, el)
            end
            table.insert(right, { Text = " " })

            win:set_right_status(wezterm.format(right))
          end)
        end

        return M

        """;
}
