using System.Text;
using Fleet.Platform.Mux.WezTerm.Models;
using Fleet.Shared.Keymap;
using Fleet.Shared.Keymap.Enums;
using Fleet.Ui;

namespace Fleet.Platform.Mux.WezTerm;

public static class WezTermKeybinds
{
    private static readonly FleetAction[] MenuActions =
    [
        FleetAction.NewAgent,
        FleetAction.ChangeHarness,
        FleetAction.ToggleHidden,
        FleetAction.RemoveAgent,
        FleetAction.AddRepository,
        FleetAction.RemoveRepository,
        FleetAction.EditKeybinds,
        FleetAction.OpenProject,
        FleetAction.Close,
    ];

    public static string Generate(Keymap keymap, string fleetExecutable, string workspaceRequest)
    {
        var chord = WezTermChord.From(keymap.PrefixText);
        var exe = fleetExecutable.Replace("\\", "\\\\", StringComparison.Ordinal);
        var request = workspaceRequest.Replace("\\", "\\\\", StringComparison.Ordinal);

        var sb = new StringBuilder();

        sb.AppendLine("-- generated by: fleet apply-keybinds");
        sb.AppendLine("-- edit fleet's keybinds instead of this file; it is overwritten.");
        sb.AppendLine("--");
        sb.AppendLine("-- add to .wezterm.lua:");
        sb.AppendLine("--   local fleet = require 'fleet'");
        sb.AppendLine("--   fleet.apply(config)");
        sb.AppendLine();
        sb.AppendLine("local wezterm = require 'wezterm'");
        sb.AppendLine("local act = wezterm.action");
        sb.AppendLine();
        sb.AppendLine("local M = {}");
        sb.AppendLine();
        sb.AppendLine($"M.fleet = '{exe}'");
        sb.AppendLine();
        sb.AppendLine("-- The menu belongs to windows fleet is actually running in. A fleet dashboard");
        sb.AppendLine("-- marks its pane with a WezTerm user var holding the project name; without one");
        sb.AppendLine("-- the chord is forwarded to the pane untouched, so unrelated windows keep the");
        sb.AppendLine("-- key.");
        sb.AppendLine("local function fleet_project(window)");
        sb.AppendLine("  local ok, tabs = pcall(function()");
        sb.AppendLine("    return window:mux_window():tabs()");
        sb.AppendLine("  end)");
        sb.AppendLine();
        sb.AppendLine("  if not ok or not tabs then");
        sb.AppendLine("    return nil");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  for _, tab in ipairs(tabs) do");
        sb.AppendLine("    for _, p in ipairs(tab:panes()) do");
        sb.AppendLine("      local vars = p:get_user_vars()");
        sb.AppendLine($"      local project = vars and vars['{WezTermUserVars.FleetVar}']");
        sb.AppendLine("      if project and project ~= '' then");
        sb.AppendLine("        wezterm.log_info('fleet: dashboard pane found for ' .. project)");
        sb.AppendLine("        return project");
        sb.AppendLine("      end");
        sb.AppendLine("    end");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  wezterm.log_info('fleet: no dashboard pane in this window, forwarding the key')");
        sb.AppendLine("  return nil");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("-- Actions the running dashboard renders itself. Sending these to the dashboard");
        sb.AppendLine("-- keeps the form inside the pane it belongs to instead of squeezing a third");
        sb.AppendLine("-- column into the window.");
        sb.AppendLine("M.dashboard_actions = {");

        foreach (var action in MenuActions.Where(DashboardActions.IsServed))
        {
            sb.AppendLine($"  ['{FleetActionIds.For(action)}'] = true,");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("-- The CLI cannot switch workspaces: activate-pane reports success but leaves");
        sb.AppendLine("-- the client where it was. Hidden agents live in their own workspace, so fleet");
        sb.AppendLine("-- asks for a switch by writing a file and this handler performs it. update-status");
        sb.AppendLine("-- fires about once a second, which is the only timer wezterm offers.");
        sb.AppendLine($"M.workspace_request = '{request}'");
        sb.AppendLine();
        sb.AppendLine("wezterm.on('update-status', function(window, _pane)");
        sb.AppendLine("  local handle = io.open(M.workspace_request, 'r')");
        sb.AppendLine();
        sb.AppendLine("  if not handle then");
        sb.AppendLine("    return");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  local wanted = handle:read('*a')");
        sb.AppendLine("  handle:close()");
        sb.AppendLine("  os.remove(M.workspace_request)");
        sb.AppendLine();
        sb.AppendLine("  wanted = wanted and wanted:gsub('%s+$', '')");
        sb.AppendLine();
        sb.AppendLine("  if not wanted or wanted == '' then");
        sb.AppendLine("    return");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  if window:active_workspace() == wanted then");
        sb.AppendLine("    return");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  wezterm.log_info('fleet: switching to workspace ' .. wanted)");
        sb.AppendLine("  window:perform_action(act.SwitchToWorkspace { name = wanted }, _pane)");
        sb.AppendLine("end)");
        sb.AppendLine();
        sb.AppendLine("function M.apply(config)");
        sb.AppendLine("  config.keys = config.keys or {}");
        sb.AppendLine();
        sb.AppendLine("  table.insert(config.keys, {");
        sb.AppendLine($"    key = '{chord.Key}',");
        sb.AppendLine($"    mods = '{chord.Mods}',");
        sb.AppendLine("    action = wezterm.action_callback(function(window, pane)");
        sb.AppendLine("      if not fleet_project(window) then");
        sb.AppendLine("        window:perform_action(");
        sb.AppendLine($"          act.SendKey {{ key = '{chord.Key}', mods = '{chord.Mods}' }},");
        sb.AppendLine("          pane");
        sb.AppendLine("        )");
        sb.AppendLine("        return");
        sb.AppendLine("      end");
        sb.AppendLine();
        sb.AppendLine("      window:perform_action(");
        sb.AppendLine("        act.InputSelector {");
        sb.AppendLine("          title = 'fleet',");
        sb.AppendLine("          fuzzy = true,");
        sb.AppendLine("          choices = {");

        foreach (var action in MenuActions)
        {
            var label = KeymapDefaults.Describe(action);
            var id = FleetActionIds.For(action);
            sb.AppendLine($"            {{ label = '{label}', id = '{id}' }},");
        }

        sb.AppendLine("          },");
        sb.AppendLine("          action = wezterm.action_callback(function(inner, target, id, _label)");
        sb.AppendLine("            if not id then");
        sb.AppendLine("              return");
        sb.AppendLine("            end");
        sb.AppendLine();
        sb.AppendLine("            local project = fleet_project(inner)");
        sb.AppendLine();
        sb.AppendLine("            if project and M.dashboard_actions[id] then");
        sb.AppendLine("              wezterm.background_child_process {");
        sb.AppendLine("                M.fleet, 'request', '--action', id, '--project', project,");
        sb.AppendLine("              }");
        sb.AppendLine("              return");
        sb.AppendLine("            end");
        sb.AppendLine();
        sb.AppendLine("            inner:perform_action(");
        sb.AppendLine("              act.SplitPane {");
        sb.AppendLine("                direction = 'Right',");
        sb.AppendLine("                size = { Percent = 45 },");
        sb.AppendLine("                command = { args = { M.fleet, 'menu', '--action', id } },");
        sb.AppendLine("              },");
        sb.AppendLine("              target");
        sb.AppendLine("            )");
        sb.AppendLine("          end),");
        sb.AppendLine("        },");
        sb.AppendLine("        pane");
        sb.AppendLine("      )");
        sb.AppendLine("    end),");
        sb.AppendLine("  })");
        sb.AppendLine();
        sb.AppendLine("  return config");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("-- Compatibility with the predecessor's call shape. A .wezterm.lua written for");
        sb.AppendLine("-- the old Go fleet calls fleet.setup(config, opts); its pcall guards only the");
        sb.AppendLine("-- require, so a module without setup would fail the whole config at load.");
        sb.AppendLine("function M.setup(config, _opts)");
        sb.AppendLine("  return M.apply(config)");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("return M");

        return sb.ToString();
    }
}
