using Fleet.Shared.Keymap.Enums;

namespace Fleet.Shared.Keymap;

public static class FleetActionIds
{

    public static string For(FleetAction action) => action switch
    {
        FleetAction.AddRepository => "add-repository",
        FleetAction.EditKeybinds => "keybinds",
        FleetAction.EditShowMenuKeys => "show-menu-keys",
        FleetAction.EditButtonHints => "button-hints",
        FleetAction.RevealMenuKeys => "reveal-menu-keys",
        FleetAction.HoldMenuKeys => "hold-menu-keys",
        FleetAction.OpenProject => "open-project",
        FleetAction.NewProject => "new-project",
        FleetAction.Refresh => "refresh",
        FleetAction.NewAgent => "new-agent",
        FleetAction.ChangeHarness => "change-harness",
        FleetAction.ToggleHidden => "toggle-hidden",
        FleetAction.StopAgent => "stop-agent",
        FleetAction.RemoveAgent => "remove-agent",
        FleetAction.RemoveRepository => "remove-repository",
        FleetAction.PullRepository => "pull-repository",
        FleetAction.ManageRepository => "manage-repository",
        FleetAction.QuitFleet => "quit",
        FleetAction.FocusMain => "main-pane",
        FleetAction.ListAgents => "list-agents",
        FleetAction.EditSettings => "settings",
        FleetAction.SwitchProject => "switch-project",
        FleetAction.CleanupProject => "cleanup",
        FleetAction.RebuildDashboard => "rebuild-dashboard",
        FleetAction.EditFleetConfig => "edit-fleet-config",
        FleetAction.OpenSettings => "settings-menu",
        FleetAction.OpenFleetConfigMenu => "fleet-config-menu",
        FleetAction.EditAidlcMode => "aidlc-mode",
        FleetAction.EditAutoClose => "auto-close",
        FleetAction.EditClaudeProfile => "claude-profile",
        FleetAction.EditMainOrchestratorInNvim => "main-orchestrator-nvim",
        FleetAction.EditSubOrchestratorsInNvim => "sub-orchestrators-nvim",
        FleetAction.EditNvimConfig => "nvim-config",
        FleetAction.EditHeadModel => "head-model",
        FleetAction.EditMainModel => "main-model",
        FleetAction.EditSubModel => "sub-model",
        FleetAction.EditAgentModel => "agent-model",
        FleetAction.Notifications => "notifications",
        FleetAction.Remotes => "remotes",
        FleetAction.SaveSession => "save-session",
        FleetAction.DismissNotice => "dismiss-notice",
        FleetAction.DismissAllNotices => "dismiss-all-notices",
        FleetAction.OpenEditor => "open-editor",
        FleetAction.OpenHeadVoice => "head-voice",
        FleetAction.EditTheme => "theme",
        FleetAction.UpdateFleet => "update",
        FleetAction.ShowVersion => "version",
        FleetAction.WhatsNew => "whats-new",
        FleetAction.HideAllAgents => "hide-all",
        FleetAction.OpenWebApp => "open-web-app",
        _ => action.ToString().ToLowerInvariant(),
    };

    public static FleetAction Parse(string id) => id.Trim().ToLowerInvariant() switch
    {
        "add-repository" => FleetAction.AddRepository,
        "keybinds" => FleetAction.EditKeybinds,
        "show-menu-keys" => FleetAction.EditShowMenuKeys,
        "button-hints" => FleetAction.EditButtonHints,
        "reveal-menu-keys" => FleetAction.RevealMenuKeys,
        "hold-menu-keys" => FleetAction.HoldMenuKeys,
        "open-project" => FleetAction.OpenProject,
        "new-project" => FleetAction.NewProject,
        "refresh" => FleetAction.Refresh,
        "new-agent" => FleetAction.NewAgent,
        "change-harness" => FleetAction.ChangeHarness,
        "toggle-hidden" => FleetAction.ToggleHidden,
        "stop-agent" => FleetAction.StopAgent,
        "remove-agent" => FleetAction.RemoveAgent,
        "remove-repository" => FleetAction.RemoveRepository,
        "pull-repository" => FleetAction.PullRepository,
        "manage-repository" => FleetAction.ManageRepository,
        "quit" => FleetAction.QuitFleet,
        "main-pane" => FleetAction.FocusMain,
        "list-agents" => FleetAction.ListAgents,
        "settings" => FleetAction.EditSettings,
        "switch-project" => FleetAction.SwitchProject,
        "cleanup" => FleetAction.CleanupProject,
        "rebuild-dashboard" => FleetAction.RebuildDashboard,
        "edit-fleet-config" => FleetAction.EditFleetConfig,
        "settings-menu" => FleetAction.OpenSettings,
        "fleet-config-menu" => FleetAction.OpenFleetConfigMenu,
        "aidlc-mode" => FleetAction.EditAidlcMode,
        "auto-close" => FleetAction.EditAutoClose,
        "claude-profile" => FleetAction.EditClaudeProfile,
        "main-orchestrator-nvim" => FleetAction.EditMainOrchestratorInNvim,
        "sub-orchestrators-nvim" => FleetAction.EditSubOrchestratorsInNvim,
        "nvim-config" => FleetAction.EditNvimConfig,
        "head-model" => FleetAction.EditHeadModel,
        "main-model" => FleetAction.EditMainModel,
        "sub-model" => FleetAction.EditSubModel,
        "agent-model" => FleetAction.EditAgentModel,
        "notifications" => FleetAction.Notifications,
        "remotes" => FleetAction.Remotes,
        "save-session" => FleetAction.SaveSession,
        "dismiss-notice" => FleetAction.DismissNotice,
        "dismiss-all-notices" => FleetAction.DismissAllNotices,
        "open-editor" => FleetAction.OpenEditor,
        "head" => FleetAction.OpenHeadVoice,
        "head-voice" => FleetAction.OpenHeadVoice,
        "theme" => FleetAction.EditTheme,
        "whats-new" => FleetAction.WhatsNew,
        "hide-all" => FleetAction.HideAllAgents,
        "open-web-app" => FleetAction.OpenWebApp,
        "close" => FleetAction.Close,
        var other => Enum.GetValues<FleetAction>().FirstOrDefault(a => For(a) == other),
    };
}
