using Fleet.Shared.Keymap.Enums;

namespace Fleet.Shared.Keymap;

public static class KeymapDefaults
{
    public const string Prefix = "Ctrl+Enter";

    public static IReadOnlyDictionary<FleetAction, string> Bindings { get; } =
        new Dictionary<FleetAction, string>
        {
            [FleetAction.OpenMenu] = "Space",
            [FleetAction.NewProject] = "n",
            [FleetAction.RemoveProject] = "d",
            [FleetAction.OpenProject] = "l",
            [FleetAction.Refresh] = "r",
            [FleetAction.EditKeybinds] = "k",
            [FleetAction.EditShowMenuKeys] = "K",
            [FleetAction.EditButtonHints] = "t",
            [FleetAction.RevealMenuKeys] = "?",
            [FleetAction.HoldMenuKeys] = "/",
            [FleetAction.Close] = "q",
            [FleetAction.MoveDown] = "j",
            [FleetAction.MoveUp] = "k",
            [FleetAction.MoveFirst] = "g",
            [FleetAction.MoveLast] = "G",
            [FleetAction.PageDown] = "Ctrl+D",
            [FleetAction.PageUp] = "Ctrl+U",
            [FleetAction.PrevTab] = "h",
            [FleetAction.NextTab] = "l",
            [FleetAction.NewAgent] = "n",
            [FleetAction.RemoveAgent] = "m",
            [FleetAction.ToggleHidden] = "x",
            [FleetAction.AddRepository] = "n",
            [FleetAction.RemoveRepository] = "d",
            [FleetAction.PullRepository] = "p",
            [FleetAction.ManageRepository] = "m",
            [FleetAction.QuitFleet] = "Q",
            [FleetAction.FocusMain] = "m",
            [FleetAction.ListAgents] = "l",
            [FleetAction.ViewLogs] = "l",
            [FleetAction.BrowseFiles] = "f",
            [FleetAction.EditSettings] = "p",
            [FleetAction.SwitchProject] = "p",
            [FleetAction.CleanupProject] = "x",
            [FleetAction.RebuildDashboard] = "b",
            [FleetAction.EditFleetConfig] = "e",
            [FleetAction.OpenSettings] = "s",
            [FleetAction.OpenFleetConfigMenu] = "c",
            [FleetAction.EditAidlcMode] = "A",
            [FleetAction.EditAutoClose] = "i",
            [FleetAction.EditClaudeProfile] = "C",
            [FleetAction.EditMainOrchestratorInNvim] = "v",
            [FleetAction.EditSubOrchestratorsInNvim] = "V",
            [FleetAction.EditNvimConfig] = "N",
            [FleetAction.EditHeadModel] = "H",
            [FleetAction.EditMainModel] = "M",
            [FleetAction.EditSubModel] = "S",
            [FleetAction.EditAgentModel] = "R",
            [FleetAction.Notifications] = "n",
            [FleetAction.Remotes] = "r",
            [FleetAction.SaveSession] = "w",
            [FleetAction.DismissNotice] = "d",
            [FleetAction.DismissAllNotices] = "D",
            [FleetAction.OpenEditor] = "e",
            [FleetAction.OpenHeadVoice] = "Alt+o",
            [FleetAction.EditTheme] = "T",
        };

    public static IReadOnlyList<FleetAction> Configurable { get; } =
        [.. KeymapGroups.All.SelectMany(g => g.Actions)];

    public static string Short(FleetAction action) =>
        action switch
        {
            FleetAction.RemoveProject => "drop project",
            FleetAction.NewAgent => "new agent",
            FleetAction.ChangeHarness => "opens",
            FleetAction.ToggleHidden => "hide",
            FleetAction.RemoveAgent => "manage",
            FleetAction.AddRepository => "add repo",
            FleetAction.RemoveRepository => "drop repo",
            FleetAction.PullRepository => "pull",
            FleetAction.ManageRepository => "manage repo",
            FleetAction.EditKeybinds => "keybinds",
            FleetAction.EditShowMenuKeys => "show keys",
            FleetAction.EditButtonHints => "button hints",
            FleetAction.RevealMenuKeys => "reveal keys",
            FleetAction.HoldMenuKeys => "hold for keys",
            FleetAction.OpenProject => "project",
            FleetAction.Refresh => "refresh",
            FleetAction.Close => "close pane",
            FleetAction.QuitFleet => "quit fleet",
            FleetAction.FocusMain => "dashboard",
            FleetAction.ListAgents => "list agents",
            FleetAction.ViewLogs => "logs",
            FleetAction.BrowseFiles => "files",
            FleetAction.EditSettings => "permissions",
            FleetAction.SwitchProject => "switch project",
            FleetAction.CleanupProject => "clean up",
            FleetAction.RebuildDashboard => "rebuild dash",
            FleetAction.EditFleetConfig => "edit fleet config file",
            FleetAction.OpenSettings => "settings",
            FleetAction.OpenFleetConfigMenu => "fleet config",
            FleetAction.EditAidlcMode => "aidlc",
            FleetAction.EditAutoClose => "auto-close",
            FleetAction.EditClaudeProfile => "claude profile",
            FleetAction.EditMainOrchestratorInNvim => "main in nvim",
            FleetAction.EditSubOrchestratorsInNvim => "subs in nvim",
            FleetAction.EditNvimConfig => "nvim config",
            FleetAction.EditHeadModel => "head model",
            FleetAction.EditMainModel => "main model",
            FleetAction.EditSubModel => "sub model",
            FleetAction.EditAgentModel => "agent model",
            FleetAction.Notifications => "notifications",
            FleetAction.Remotes => "remotes",
            FleetAction.SaveSession => "save session",
            FleetAction.DismissNotice => "dismiss",
            FleetAction.DismissAllNotices => "dismiss all",
            FleetAction.OpenEditor => "editor",
            FleetAction.OpenHeadVoice => "head",
            FleetAction.EditTheme => "theme",
            _ => Describe(action).ToLowerInvariant(),
        };

    public static string Describe(FleetAction action) =>
        action switch
        {
            FleetAction.OpenMenu => "Open the fleet menu",
            FleetAction.NewProject => "New project",
            FleetAction.RemoveProject => "Remove a project from fleet",
            FleetAction.OpenProject => "Open selection",
            FleetAction.AddRepository => "Add repository",
            FleetAction.Refresh => "Refresh",
            FleetAction.EditKeybinds => "Keybinds",
            FleetAction.EditShowMenuKeys => "Show keybinds in menus",
            FleetAction.EditButtonHints => "How buttons explain themselves: text, tooltips or none",
            FleetAction.RevealMenuKeys => "Show or hide keybinds",
            FleetAction.HoldMenuKeys => "Show keybinds while held",
            FleetAction.Close => "Close this pane",
            FleetAction.MoveDown => "Move down",
            FleetAction.MoveUp => "Move up",
            FleetAction.MoveFirst => "Jump to first",
            FleetAction.MoveLast => "Jump to last",
            FleetAction.PageDown => "Page down",
            FleetAction.PageUp => "Page up",
            FleetAction.PrevTab => "Previous tab",
            FleetAction.NextTab => "Next tab",
            FleetAction.NewAgent => "New agent",
            FleetAction.ChangeHarness => "Change what an agent opens",
            FleetAction.ToggleHidden => "Hide or show an agent in the terminal",
            FleetAction.StopAgent => "Stop an agent",
            FleetAction.RemoveAgent => "Manage an agent",
            FleetAction.RemoveRepository => "Remove a repository",
            FleetAction.PullRepository => "Pull the repository",
            FleetAction.ManageRepository => "Manage the repository",
            FleetAction.QuitFleet => "Quit fleet",
            FleetAction.FocusMain => "Go to dashboard",
            FleetAction.ListAgents => "List agents",
            FleetAction.ViewLogs => "Show log",
            FleetAction.BrowseFiles => "File navigator",
            FleetAction.EditSettings => "Permissions",
            FleetAction.SwitchProject => "Switch project",
            FleetAction.CleanupProject => "Clean up stale agents",
            FleetAction.RebuildDashboard => "Rebuild the dashboard layout",
            FleetAction.EditFleetConfig => "Edit fleet config file",
            FleetAction.OpenSettings => "Settings",
            FleetAction.OpenFleetConfigMenu => "Fleet config",
            FleetAction.EditAidlcMode => "AIDLC settings",
            FleetAction.EditAutoClose => "Auto-close idle agents",
            FleetAction.EditClaudeProfile => "Claude profile",
            FleetAction.EditMainOrchestratorInNvim => "Main orchestrator in nvim",
            FleetAction.EditSubOrchestratorsInNvim => "Sub-orchestrators in nvim",
            FleetAction.EditNvimConfig => "Nvim config",
            FleetAction.EditHeadModel => "Head model",
            FleetAction.EditMainModel => "Main orchestrator model",
            FleetAction.EditSubModel => "Sub-orchestrator model",
            FleetAction.EditAgentModel => "Repo agent model",
            FleetAction.Notifications => "Notifications",
            FleetAction.Remotes => "Remote machines",
            FleetAction.SaveSession => "Save window as session",
            FleetAction.DismissNotice => "Dismiss a notification",
            FleetAction.DismissAllNotices => "Dismiss all shown notifications",
            FleetAction.OpenEditor => "Open editor here",
            FleetAction.OpenHeadVoice => "Show or hide the head, in voice mode",
            FleetAction.EditTheme => "Theme",
            _ => action.ToString(),
        };
}
