using Fleet.Shared.Themes;

namespace Fleet.Platform.Yazi;

public static class YaziTheme
{
    public const string FileName = "theme.toml";

    public const string Header = "# generated by fleet";

    public static bool IsFleets(string text) => text.StartsWith(Header, StringComparison.Ordinal);

    public static string Generate(ThemePalette theme)
    {
        var magenta = theme.Ansi[5];
        var cyan = theme.Ansi[6];

        return $$"""
            {{Header}} from the '{{theme.Name}}' theme; fleet rewrites this file on every theme change.
            # Delete the first line to keep your own edits: fleet then leaves the file alone.

            [mgr]
            cwd = { fg = "{{cyan}}" }
            find_keyword = { fg = "{{theme.Yellow}}", bold = true, italic = true, underline = true }
            find_position = { fg = "{{magenta}}", bg = "reset", bold = true, italic = true }
            marker_copied = { fg = "{{theme.Green}}", bg = "{{theme.Green}}" }
            marker_cut = { fg = "{{theme.Red}}", bg = "{{theme.Red}}" }
            marker_marked = { fg = "{{cyan}}", bg = "{{cyan}}" }
            marker_selected = { fg = "{{theme.Yellow}}", bg = "{{theme.Yellow}}" }
            count_copied = { fg = "{{theme.Base}}", bg = "{{theme.Green}}" }
            count_cut = { fg = "{{theme.Base}}", bg = "{{theme.Red}}" }
            count_selected = { fg = "{{theme.Base}}", bg = "{{theme.Yellow}}" }
            border_style = { fg = "{{theme.Surface1}}" }

            [tabs]
            active = { fg = "{{theme.Base}}", bg = "{{theme.Blue}}", bold = true }
            inactive = { fg = "{{theme.Blue}}", bg = "{{theme.Surface0}}" }

            [mode]
            normal_main = { fg = "{{theme.Base}}", bg = "{{theme.Blue}}", bold = true }
            normal_alt = { fg = "{{theme.Blue}}", bg = "{{theme.Surface0}}" }
            select_main = { fg = "{{theme.Base}}", bg = "{{theme.Green}}", bold = true }
            select_alt = { fg = "{{theme.Green}}", bg = "{{theme.Surface0}}" }
            unset_main = { fg = "{{theme.Base}}", bg = "{{theme.Red}}", bold = true }
            unset_alt = { fg = "{{theme.Red}}", bg = "{{theme.Surface0}}" }

            [indicator]
            parent = { fg = "{{theme.Base}}", bg = "{{theme.Overlay0}}" }
            current = { fg = "{{theme.Base}}", bg = "{{theme.Lavender}}" }
            preview = { fg = "{{theme.Base}}", bg = "{{theme.Overlay0}}" }

            [status]
            perm_sep = { fg = "{{theme.Overlay0}}" }
            perm_type = { fg = "{{theme.Green}}" }
            perm_read = { fg = "{{theme.Yellow}}" }
            perm_write = { fg = "{{theme.Red}}" }
            perm_exec = { fg = "{{cyan}}" }
            progress_label = { fg = "{{theme.Text}}", bold = true }
            progress_normal = { fg = "{{theme.Blue}}", bg = "{{theme.Surface0}}" }
            progress_error = { fg = "{{theme.Red}}", bg = "{{theme.Surface0}}" }

            [which]
            mask = { bg = "{{theme.Mantle}}" }
            cand = { fg = "{{cyan}}" }
            rest = { fg = "{{theme.Overlay0}}" }
            desc = { fg = "{{magenta}}" }
            separator_style = { fg = "{{theme.Surface1}}" }

            [confirm]
            border = { fg = "{{theme.Blue}}" }
            title = { fg = "{{theme.Blue}}" }
            btn_yes = { fg = "{{theme.Base}}", bg = "{{theme.Blue}}" }

            [spot]
            border = { fg = "{{theme.Blue}}" }
            title = { fg = "{{theme.Blue}}" }
            tbl_col = { fg = "{{theme.Blue}}" }
            tbl_cell = { fg = "{{theme.Base}}", bg = "{{theme.Yellow}}" }

            [notify]
            title_info = { fg = "{{theme.Green}}" }
            title_warn = { fg = "{{theme.Yellow}}" }
            title_error = { fg = "{{theme.Red}}" }

            [pick]
            border = { fg = "{{theme.Blue}}" }
            active = { fg = "{{magenta}}", bold = true }

            [input]
            border = { fg = "{{theme.Blue}}" }
            selected = { fg = "{{theme.Base}}", bg = "{{theme.Lavender}}" }

            [cmp]
            border = { fg = "{{theme.Blue}}" }
            active = { fg = "{{theme.Base}}", bg = "{{theme.Lavender}}" }

            [tasks]
            border = { fg = "{{theme.Blue}}" }
            hovered = { fg = "{{magenta}}", bold = true }

            [help]
            border = { fg = "{{theme.Blue}}" }
            chord = { fg = "{{cyan}}" }
            hovered = { fg = "{{theme.Base}}", bg = "{{theme.Lavender}}", bold = true }

            [filetype]
            rules = [
              { mime = "**/image/*", fg = "{{theme.Yellow}}" },
              { mime = "**/{audio,video}/*", fg = "{{magenta}}" },
              { mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "{{theme.Red}}" },
              { mime = "**/application/{pdf,doc,rtf}", fg = "{{cyan}}" },
              { mime = "vfs/{absent,stale}", fg = "{{theme.Overlay0}}" },
              { url = "*", is = "orphan", bg = "{{theme.Red}}" },
              { url = "*", is = "exec", fg = "{{theme.Green}}" },
              { url = "*", is = "dummy", bg = "{{theme.Red}}" },
              { url = "*/", is = "dummy", bg = "{{theme.Red}}" },
              { url = "*/", fg = "{{theme.Blue}}" },
            ]

            """.ReplaceLineEndings("\n");
    }
}
