namespace Fleet.Shared.Keymap.Enums;

public enum FleetAction
{
    None,
    OpenMenu,
    NewProject,
    OpenProject,
    AddRepository,
    Refresh,
    EditKeybinds,
    Close,
    MoveDown,
    MoveUp,
    MoveFirst,
    MoveLast,
    PageDown,
    PageUp,
    PrevTab,
    NextTab,
    NewAgent,
    ChangeHarness,
    ToggleHidden,
    StopAgent,
    RemoveAgent,
    RemoveRepository,
    QuitFleet,
    FocusMain,
    ListAgents,
}
